### ISSUE TITLE
Missing source files.

### ISSUE THREAD

**Issue by shaobohou** [shaobohou/pearley#1]
Stringable.cpp and Stringable.h are needed for compilation.

**Comment by JohnMe** [comment]
I really woud like to try this program for an open source project is it GPL or LGPL?
Also I've trouble compiling missing NRMatrix definitions?
The two files you mentioned i think i found some where else online.

**Comment by shaobohou** [comment]
Hi JohnMe, sorry about the compilation issues, I didn't really expect anyone to take notice of this code (and the other one), so I haven't quite got around to tidying them up.

License-wise, I am willing to go for Apache 2.0 or an even more permissive license, so feel free to play around with it. I will put up the license file later today, and the same goes for the two missing files.

Btw, where are you seeing this NRMatrix definition being referenced? It shouldn't be there.

**Comment by shaobohou** [comment]
It compiles now and I have added some test files to reproduce the result in the README.

**Comment by shaobohou** [comment]
A (zlib) license file has been added.

**Comment by JohnMe** [comment]
Can confirm sucessful compilation under ubuntu 10.04lts. Thank you very much.

**Comment by shaobohou** [comment]
Hi JohnMe, apologies, I accidentally blocked you (unblocked now) while I was looking at your profile.

Apparently if you clicked on the gear symbol on someone's profile, the "block user" option appears directly underneath it.

**Comment by ghost** [comment]
Hi, how can I compile your code from terminal?
Please write execution string that I must digit in terminal.

Thanks a lot! :)

**Comment by ghost** [comment]
An other question:

Does you project refer to this report?
http://www.aclweb.org/anthology/J95-2002

Thanks!

**Comment by shaobohou** [comment]
install qmake then type:

qmake && make

**Comment by shaobohou** [comment]
That link looks like the right report, though it is been a while since I read it.

**Comment by ghost** [comment]
Thanks a lot! You're the best! 😃

**Comment by ghost** [comment]
Can you help me to realise an explicit implementation of the method for the generation of the subsequent prefixes for a given input string? That is, for every symbol of the input string, the method must returning a list of possible subsequent symbols with their probability generated by initial grammar.
For example:

- Grammar Rules

0 = S --> NP VP   [1]
1 = NP --> Det N   [1]
2 = VP --> VT NP   [0.5]
3 = VP --> VI PP   [0.5]
4 = PP --> P NP   [1]
5 = Det --> a   [1]
6 = N --> circle   [0.333333]
7 = N --> square   [0.333333]
8 = N --> triangle   [0.333333]
9 = VT --> touches   [1]
10 = VI --> is   [1]
11 = P --> above   [0.5]
12 = P --> below   [0.5]

- Input string

a circle touches a triangle

The method returns:

1) List("a") = {("circle", 0.333333), ("square", 0.333333), ("triangle", 0.333333)}, where 0.333333 is a probability of "a"

2) List("circle") = {("circle", 0.333333)}, generates itself
3) List("touches") = {("touches", 0.333333)}, generates itself
4) List("a") = like 1)
5) List("triangle") = {("triangle", 0.333333)}, generates itself.

Thanks a lot in advance!

P. S. your works in github are wonderful!!

Sincerely

Dan
